### ISSUE TITLE
[96455ca] Audio capture is broken

### ISSUE THREAD

**Issue by LordHDL** [zakk4223/CocoaSplit#60]
Test recording: https://www.dropbox.com/s/s5mw3m0dpc6n78y/No%20Audio.mp4?dl=0

**Comment by zakk4223** [comment]
None of the audio inputs are active there. Click the 'on' button below them to make them active.

That said, I'm open to suggestions on how to better setup that UI; it's pretty barebones and not at all good right now.

**Comment by LordHDL** [comment]
Hmm, could've sworn I had tried that.

I do have a suggestion.  Currently it looks a bit ambiguous in that you can't tell if it's on or not (until you've learned it, at least).  The button "On" made me think it was active, when it apparently means it'll turn on once you click it (and it says "Off").

If you look in Xcode in the Capabilities tab, you'll see sliders on the right where the word Off is against a gray background.  If you slide it you'll see the word On against a bright blue.

Anyway my point is not that you should copy that necessarily, but rather it's a good example of less ambiguity; mistaking Off for On or vice versa is unlikely.

Another approach would be if you reverse the button so it says Off when off against a dark gray background, while On would be against a green one to indicate it's active.
