### ISSUE TITLE
[96455ca] Strange colors with Syphon injected sources

### ISSUE THREAD

**Issue by LordHDL** [zakk4223/CocoaSplit#61]
![screen shot 2015-02-15 at 10 09 01 am](https://cloud.githubusercontent.com/assets/5182602/6203729/104774fe-b4fe-11e4-8ddb-843e227caf55.png)

**Comment by zakk4223** [comment]
What application are you injecting?

**Comment by LordHDL** [comment]
This one was Norichan, though I've tested a few others (same result).  They appear normally in Syphon Recorder.

**Comment by zakk4223** [comment]
Try commit 23162314c0, I redid how Syphon sources are rendered.
