### ISSUE TITLE
[7e3cb56] Delay and visual artifacts when switching to different resolution

### ISSUE THREAD

**Issue by LordHDL** [zakk4223/CocoaSplit#66]
If you switch between 2 layouts of different resolutions while streaming/recording, there will be a delay in transition along with garbled graphics.  Should probably disallow this type of transition.

**Comment by zakk4223** [comment]
See if things are better with the latest commit, there was part of the rendering code that was ignoring the layout dimensions so weird stuff would happen .

**Comment by LordHDL** [comment]
Seems to work fine now.  There's still a minor oddity but it's hardly noticeable.  I'll point it out just to make it known.

![vlcsnap-00001](https://cloud.githubusercontent.com/assets/5182602/6252187/810205dc-b766-11e4-9c37-b8e79de548f8.png)

After switching there is 1 frame where you see something like this before the shot turns black and then fades into the next layout.  This only happens the 1st time you switch.
