### ISSUE TITLE
[e302a3b] Rate change doesn't affect quality using CBR

### ISSUE THREAD

**Issue by LordHDL** [zakk4223/CocoaSplit#73]
Example video: https://www.dropbox.com/s/lq7tcbeljn8riw3/CS%20Rate%20Change.mp4.gz?dl=0

I started with 5000 bit rate and dropped it to around 300 or so.  The video quality remains as if it were 5000, and there is some visual flickering after the change.

This was when using CBR.  The rate change worked correctly using CRF.

**Comment by zakk4223** [comment]
What’s the compressor config look like? Also make sure you are compiling against a new ffmpeg AND x264. The CBR mode uses an x264 parameter that didn’t show up until around x264 build 139 I think. (current build is 146)

**Comment by LordHDL** [comment]
My x264 library and ffmpeg are current git.  Compressor config:

![screen shot 2015-02-28 at 8 00 24 pm](https://cloud.githubusercontent.com/assets/5182602/6428968/a4fa485c-bf84-11e4-8022-93a0576a2383.png)
